language: java

jdk:
  - oraclejdk8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
after_success:
  - mvn clean test jacoco:report coveralls:report

# Migration to container-based infrastructure  
sudo: false
